[package]
name = "actix-session"
version = "0.5.0-beta.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Sessions for Actix web"
readme = "README.md"
keywords = ["http", "web", "framework", "async", "session"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-extras"
documentation = "https://docs.rs/actix-session/"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "actix_session"
path = "src/lib.rs"

[features]
default = ["cookie-session"]
cookie-session = ["actix-web/secure-cookies"]

[dependencies]
actix-web = { version = "4.0.0-beta.6", default_features = false, features = ["cookies"] }
actix-service = "2.0.0"

derive_more = "0.99.13"
futures-util = { version = "0.3.14", default-features = false }
log = "0.4.14"
serde = "1.0.125"
serde_json = "1.0.64"
time = "0.2.26"

[dev-dependencies]
actix-rt = "2.2.0"
